opentrials/api

- api/controllers/locations.js
- api/controllers/search.js
- api/swagger/swagger.yaml
- test/api/controllers/locations.js
- tools/create-trials-index.js
_Related to https://github.com/opentrials/opentrials/pull/33. Fixes #13._
There were only two things needed here: add a `/locations` endpoint, so the opentrials.net site could show a list of locations to filter by, and explicitly generating a mapping in elasticsearch.
The mapping was needed because we're using filters as part of the query string. For example, to query the results in a specific location (say Brazil), the user could simply pass `location:Brazil` (http://opentrials-api.herokuapp.com/v1/search?q=location:Brazil). This was inspired by GitHub's search qualifiers (check https://developer.github.com/v3/search/#search-issues), although it doesn't work the same way yet. For example, the default operator is `OR`, which means that a query for `osteoporosis location:Brazil` will …
> Search filters

- api/swagger/swagger.yaml
- config/default.yaml
- server.js
- test/integration/server.js
To test it you can use:
> curl -s -H "Origin: http://foo.com" -v http://opentrials-api.herokuapp.com/v1/swagger.yaml > /dev/null
You should see `Access-Control-Allow-Origin: *` in the response's headers.
You can also use http://petstore.swagger.io/ adding `http://opentrials-api.herokuapp.com/v1/swagger.yaml` into the text input in the header and clicking on "Explore".
Fixes #11
> [#11] Enable CORS

- docker-compose.yml
- tools/create-trials-index.js
That's the latest version supported on AWS
> [#27] Downgrade ElasticSearch to 1.5.2

- api/swagger/swagger.yaml
- test/api/controllers/search.js
There're performance issues on paginating too many results. GitHub limits
1,000 results per query, for example. I would like to do the same, but that
would require validating on two query parameters (`page` and `per_page`). It's
easier to simply limit on a single parameter, so that's what I've done here. If
we have performance issues, we can improve on this solution.
In the worst case, a user would be able to get 100 pages with 100 results each,
totaling 10,000 results.
Fixes opentrials/opentrials#65
Related to https://github.com/opentrials/opentrials/commit/593b0776a2b7b8702cf35d887fd2e703333f279a
> [#65] Return at most 100 pages

- api/models/condition.js
- api/models/intervention.js
- api/models/location.js
- api/models/organisation.js
- api/models/person.js
- api/swagger/swagger.yaml
- test/api/models/condition.js
- test/api/models/intervention.js
- test/api/models/location.js
- test/api/models/organisation.js
- test/api/models/person.js
- tools/create-trials-index.js
Every entity now has an `url` attribute which points to their API endpoint. This is needed for https://github.com/opentrials/opentrials/issues/124.
@roll This is blocking @smth, so I'm merging it. Please take a look when you can :+1:
> Add urls to entities

- migrations/20160527115742_fix_records_unique_constraint.js
Current constraint is wrong because for example `source_id=ictrp` having records from other primary registries (so database re-population was in write errors).
> fixed records unique constraint

- api/swagger/swagger.yaml
This was introduced by a58871267e3db61df8ea6e1dd83d1bc688325fbc
> Fix bug where the API spec required some fields that could be null

- api/models/trial.js
- api/swagger/swagger.yaml
- package.json
- test/api/models/trial.js
- tools/create-trials-index.js
If we don't calculate the discrepancies in the API, we'll have to do it in
the Explorer, which causes duplication because the code to check if a trial has
discrepancies is quite similar to the one to generate the discrepancies list.
opentrials/opentrials#194
> [#194] Add trial.discrepancies and remove trial.has_discrepancies

- config/index.js
- package.json
- server.js
This is generated using Swagger UI. Unfortunately, there's no way to configure
the swagger file's path in Swagger UI, so we need to directly change it in the
code. To avoid doing this change manually, I've added a small bit of code that
does it when starting the server. It's ugly and hacky, but it works for now.
> Add API docs in /v1/docs endpoint

- npm-shrinkwrap.json
* Fixes #257
* See the [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) docs for more info
> [#257] Lock down dependency versions (npm-shrinkwrap)

- api/models/document.js
- api/models/trial.js
- api/swagger/swagger.yaml
- migrations/20160708115615_remove_trials_documents_and_documents_slug_and_add_trial_id_type_and_url_to_documents.js
- seeds/trials.js
- test/api/models/trial.js
- test/common.js
We had a `trials_documents` table to generate a many-to-many relationship
between trials and documents. However, a single document can't cite multiple
trials (AFAIK), so we can simplify that to a 1-to-many relationship. This means
we can remove the `trials_documents` table.
I also removed the `documents.slug` column, as we're not using it, and added
the `type` (e.g. csr, epar_segment, ...) and `url` columns. For now, the trials
endpoint returns an array of these documents with their `name`, `type` and
`url`.
opentrials/opentrials#254
> [#254] Returns documents and change relationship between it and trials

- tools/create-trials-index.js
After several iterations, I found this current implementation as being the fastest and more reliable of all the different ideas I had for it. No need for dedicated methods, helpers etc., as all our autocomplete models now have a relationship with trials.
~~Changed the console text a bit too, in order to reflect the total number that is just being processed for indexing, and not necessarily everything is going to be (re)indexed.~~ I tried to play with the console text a bit, but I managed to get eslint angry instead. :fearful:
> [#301] Don't index entities not linked to trials

- api/models/trial.js
- test/api/models/trial.js
They cause too much trouble because they have translations in different
languages, the `registration_date` is different for each country, the
`target_sample_size` is specific to each country, etc.. To avoid those, we'll
just ignore EUCTR completely for now.
Fixes opentrials/opentrials#278
> [#278] Ignore EUCTR records when calculating discrepancies

- migrations/20160830191612_add_on_delete_cascade_to_trials_relationship_tables.js
Added this only for the "trial_id", and not the other foreign keys (e.g.
publication_id on trials_publications) to be safer. Also, removing a trial with
all those different relations is cumbersome, but removing a (say) publication
isn't because we just need to remove the trials_publications referencing it.
> Add ON DELETE CASCADE to all trials relationship tables

- migrations/20160831135725_create_fda_applications.js
We now have a new "fda_applications" table which will contain metadata for
every FDA application. The "interventions" and "fda_approvals" tables now
references it through their "fda_application_id" columns.
The complexity of this migration is to maintain the existing relationships.
For this reason, I had to set all "fda_applications" columns as nullable, even
though they shouldn't be null. This way, I can create the rows just needing the
IDs (i.e. the FDA application numbers), which we already have in the DB.
When this migration is applied and we have all data in the DB, we should add
the "NOT NULL" constraints.
opentrials/opentrials#361
> [#361] Add fda_applications and its references

- tools/create-trials-index.js
I did so by offloading the removal of entities without trials to the database,
instead of doing it with NodeJS. With these changes, there's no need to query
for the actual trials as well, so it reduces the number of SQL queries in half.
I haven't tested the difference in memory usage, but considering we're both not
loading the trials in memory and loading just the entities we need, I'd imagine
it to be quite significant. Hopefully enough to avoid the Out of Memory errors
we're seeing.
Fixes opentrials/opentrials#364
> [#364] Reduce memory usage of the reindexing process

- api/models/document.js
- api/models/file.js
- api/models/trial.js
- api/swagger/swagger.yaml
- migrations/20160907170328_create_files_belonging_to_many_documents.js
- seeds/trials.js
- test/api/models/document.js
- test/api/models/trial.js
- test/common.js
- test/factory.js
This extracts the attributes related to the actual file location and its text
from the `documents` table to a new `files` table. The reasoning behind it is
that multiple documents can (and do) reference the same file, so this
extraction will allow us to keep a single entry in our database in those cases.
I haven't removed the columns from the `documents` table yet because I want to
populate the `files` table with our current contents before that. After we run
this migration and populate the `files` table, we can add another migration to
remove the then redudant columns.
I also changed to use the "documentcloud_id" instead of its URL so we can
delete files from DocumentCloud as needed (e.g. when they're updated). This
isn't ideal, but we can generate a document's URL based on its ID.
The …
> [#387] Add entity File that belongs to many Documents

- .travis.yml
- seeds/trials.js
The problems happen when we delete/create tables in the wrong order and end up
with a Postgres error. This commit fixes the current seeds and run them twice
on Travis, so those mistakes will end up in a failed build.
> Fix seeds and make sure Travis catches these erros in the future

- api/models/location.js
- api/swagger/swagger.yaml
- test/api/models/location.js
Locations have no `/v1/locations/<id>` route, so the URLs don't exist.
Fixes opentrials/opentrials#382
> [#382] Remove `url` from Locations API response

- api/models/publication.js
- api/models/record.js
- api/models/trial.js
- api/swagger/swagger.yaml
- seeds/trials.js
- test/api/models/publication.js
- test/api/models/record.js
- test/api/models/trial.js
- test/factory.js
See https://github.com/opentrials/opentrials/issues/327 for the reasoning behind this.
> Return all trial's sources metadata in trials.sources object

- package.json
NodeJS uses up to 1.5GB by default, but we only have 512MB available in Heroku.
Fixes opentrials/opentrials#418
> [#418] Limit memory usage when reindexing

- api/models/document.js
- migrations/20161001173327_add_url_to_documents_without_files.js
- test/api/models/document.js
- test/factory.js
A document doesn't need to be a file. It can be a webpage, for example.
Related to https://github.com/opentrials/processors/pull/66
Fixes opentrials/opentrials#429
> [#429] A document must have a "url" or a "file_id", but not both

- api/swagger/swagger.yaml
- test/api/controllers/search.js
- test/factory.js
Python's Bravado (and possibly others) complains if we don't have explicit
types, even though the Swagger validator doesn't require one.
Fixes opentrials/opentrials#457
> [#457] Add explicit "type" in all swagger definitions

- api/controllers/search.js
Using `res.json()` calls to `JSON.stringify()` on the response. As we're
getting the response from ElasticSearch, all fields are already converted to
JSON (there're no Date classes, for example), so there's no need to call
`JSON.stringify()`.
That reduces the response time in about 50%. You can check by using:
ab -n 1000 -c 50 http://localhost:10010/v1/search
With and without this patch.
opentrials/opentrials#474
> [#474] Improve /search endpoint performance

- api/swagger/swagger.yaml
* Mention that `q` is an Elasticsearch query string
Fixes opentrials/opentrials#287
> [#287] More details on the search query string

- api/controllers/search.js
- config/bluebird.js
- config/index.js
- test/api/controllers/search.js
- tools/create-trials-index.js
Modifications to reindexing script for zero downtime index (re)building process.
This builds a new index, then hot swaps an alias pointing to the existing one to the newly created indices for `trials` and `autocomplete`.
New index naming convention is;
* name of the index (e.g. `trials`)
* human readable date (e.g. `2016-10-17`)
* unique timestamp (e.g. `1476700588593`)
* all separated by underscore character (e.g. `trials_2016-10-17_1476700588593`)
There are currently two aliases: `trials` and `autocomplete` pointing to the newest corresponding index.
Fixes opentrials/opentrials#491
> [#491] Create Elasticsearch aliases to use while reindexing

- api/models/trial.js
- migrations/20161020094503_add_trials_documents.js
- migrations/20161021092257_add_uniqueness_constraints_to_documents.js
- seeds/trials.js
- test/common.js
- test/factory.js
I also modified the uniqueness constraints on the documents table, to make sure we're not adding duplicated documents in our database (check the commit message for background on the reasoning). For FDA documents, I had to add the document `name` to the unique constraint, which makes it somewhat fragile (as names can change). I created issue https://github.com/opentrials/opentrials/issues/518 to discuss our options and, depending on that, we might be able to remove the `name` from the constraint in the future.
Related to https://github.com/opentrials/processors/pull/73.
opentrials/opentrials#507
> [#507] Modify trials/documents relationship to be n-to-m instead of 1-to-n

- migrations/20161021092257_add_uniqueness_constraints_to_documents.js
- migrations/20161024144543_rename_documents_files_and_sources_url_to_source_url.js
We should never alter migrations, but I realized the ones we have now will not
work on production. The problem is that our uniqueness constraints are
different for FDA documents and non-FDA documents. This is a very clear signal
that we should have a separate FDA document entity (see
opentrials/opentrials#521). We don't have it now, so this is the best we can
do.
> Fix documents uniqueness constraints

- api/controllers/documents.js
- api/models/document.js
- api/models/trial.js
- api/swagger/swagger.yaml
- test/api/controllers/documents.js
- test/api/models/document.js
- test/api/models/trial.js
- tools/create-trials-index.js
Warning: this introduces a breaking change on the returned sources list for a trial, which is now an array on unique elements as opposed to a hash keyed by `source_id`.
The `sources` virtual now also collects sources from `documents` and adds them to the list.
Swagger definitions and tests modified accordingly.
**Note:** I'm quite happy for moving towards lists of things that are actually sets/arrays, which is likely more predictable from an user's PoV. I wouldn't really expect `trial.sources` to give me back an object :)
**Note 2:** Special attention to be paid by reviewer to the other potentially overlooked usages of `sources` ex-object, now array, throughout the code. If something is missing, it won't be observable from the PR diff alone.
> [#425] Return all sources for a trial

- api/controllers/documents.js
- api/models/document.js
- api/swagger/swagger.yaml
- test/api/controllers/documents.js
- test/api/models/document.js
We have some documents without `source_id` that came from data contributions.
We'll change them to include the original sources, but while we don't do that,
we need to allow nullable fields.
opentrials/opentrials#499
Related to opentrials/opentrials#530
> [#499] Remove extra fields from DocumentSummary and allow null source_id

- config/bluebird.js
Remove throwing on bluebird exception and trace to console as a
temporary solution.
Fixes opentrials/opentrials#527
> [#527] Fix API crash on exception

- api/swagger/swagger.yaml
- app.json
- server.js
The current problem is that the swagger clients are trying to load the API
using HTTP, instead of HTTPS. If that's on client-side, as it is on the swagger
docs page, the browser blocks those requests because they're "insecure" (mixed
content).
We could change the scheme to be HTTPS-only, but then it'll break local
development, as we don't use HTTPS while developing it on our local machines.
By removing the schemes, Swagger will use the same scheme as the one used to
load the Swagger definition. In other words, if you load the `swagger.yaml` via
HTTPS (like in production), it'll use HTTPS; if you load it via HTTP (like in
development), it'll use HTTP.
Fixes opentrials/opentrials#542
> [#542] Remove the schemes accepted in the Swagger definition

- api/models/trial.js
- test/api/models/trial.js
`document.source_id` is nullable for now. It'll change in the future (see
opentrials/opentrials#530), but for now we need to solve this bug.
Fixes opentrials/opentrials#543
> [#543] Fix bug with `trial.sources` when its documents have no source

- api/models/document.js
- test/api/models/document.js
Swagger doesn't handle `null` values well, so we end up with a schema
validation error (Expected type string but found type null).
> Remove null/undefined values from Document.toJSONSummary()

- tools/indexers/fda_documents.js
- tools/indexers/helpers.js
The documents can be quite big, so we need to go over them one per one to try
to avoid RequestEntityTooLarge errors.
Fixes opentrials/opentrials#557
> [#557] Index one document at a time

- api/controllers/search.js
- test/api/controllers/search.js
When a document has an empty page (i.e. `""`), ElasticSearch doesn't return the `highlights` attribute. In that case, we need to use the text from the page's `_source` instead.
> Fix FDA search bug on documents with empty pages

- tools/indexers/trials.js
Without this, ElasticSearch uses a different mapping that requires dates on the
format 2016-01-01 (don't accept dates like 2016-1-1). This is different from
what we have on `trials.registration_date`, so is surprising to our users.
> Add correct trial.completion_date mapping

- api/controllers/search.js
The results from the same application should be together, ordered by date. As
we're sorting descending by application number, the newer applications (with
higher numbers) will appear first.
> Sort FDA documents by application and date

- config/index.js
- config/pg_types.js
- test/api/models/trial.js
- test/config/pg_types.js
opentrials/opentrials#686
After a charming journey among the horrors of JS date handling, this is the best thing I could come up with.
Imho expressed in [this node-pg-types issue](https://github.com/brianc/node-pg-types/issues/50), the `Date`-only fields should **not** have any time information attached to them. However, seems that most JS developers (including the ones at `node-elasticsearch`) don't share my opinion so I had to settle with this for consistency.
> [#586] Fix wrong dates due to offset of time

- api/models/record.js
- api/swagger/swagger.yaml
- migrations/20161213144433_add_is_primary_to_records.js
- seeds/trials.js
- test/api/models/record.js
> [#610] Add is_primary to record

- api/models/document.js
- api/models/risk_of_bias.js
- api/models/trial.js
- test/api/models/trial.js
Fixes opentrials/opentrials#544
Fix for getting the Risk of Bias sources into the `trial.sources` virtual.
> [#544] Add Risk of Bias sources to trial

- app.json
The Bonsai add-on changed its plan name from `sandbox` to `sandbox-10`.
> Fix automatic PR deployment to Heroku

- knexfile.js
- package.json
We only allow `npm run seed` if `NODE_ENV == "production"`. This avoids us
cleaning our production database by mistake.
Fixes opentrials/opentrials#187
> [#187] Don't allow "npm run seed" in production

- api/models/document.js
- api/models/document_category.js
- api/models/trial.js
- api/swagger/swagger.yaml
- migrations/20170125115201_create_document_categories.js
- migrations/20170126145822_replace_document_type_with_document_categories.js
- seeds/trials.js
- test/api/models/document.js
- test/api/models/trial.js
- test/common.js
- test/factory.js
- tools/indexers/fda_documents.js
- tools/indexers/trials.js
> [#650] Replace document type with document category

- migrations/20170126145822_replace_document_type_with_document_categories.js
We can't add a non-nullable column without a default value to an existing table.
To do so, we need to add a nullable column, then set the data as we'd like, and
after that sets it as non-nullable.
opentrials/opentrials#650
> [#650] Fix migration that replaces document type for category

- tools/indexers/helpers.js
The error was caused by a bug on NodeJS 6.9.5 (possibly 6.x), reported on
https://github.com/nodejs/node/issues/11545.
opentrials/opentrials#693
> [#693] Fix reindexing issues

- api/controllers/document_categories.js
- api/swagger/swagger.yaml
- test/api/controllers/document_categories.js
As described in opentrials/opentrials#685, we now have an endpoint for exposing
the document categories from the API instead of storing them in Explorer.
> Add `document_categories` endpoint

- migrations/20170122130426_set_default_for_created_at_and_updated_at.js
- migrations/20170122185448_add_trigger_for_updated_at.js
- package.json
- seeds/trials.js
- test/factory.js
opentrials/opentrials#467
Currently `updated_at` and `created_at` fields are of type `TIMESTAMP WITH TIME ZONE`. Until now, we [made sure in the code that the timezone will be UTC](https://github.com/opentrials/processors/blob/master/processors/base/writers/condition.py#L33). However, after this change, if we keep the timezone, we have to [tell PostgreSQL to use UTC by editing `postgresql.conf`](https://www.postgresql.org/docs/9.1/static/runtime-config-client.html#GUC-TIMEZONE).
> [#467] Manage created_at and updated_at at db level

- migrations/20170406122708_set_study_phase_arrays_with_null_element_to_null.js
The migration that converted `study_phase` to be a `text[]` converted the
current study phases to a single-element array, including null study phases.
Because of this, we ended up with invalid study phases like `[null]`.
Fixes opentrials/opentrials#725
> [#725] Add migration to set study_phase = NULL where it's [null]

- tools/indexers/helpers.js
- tools/reindex.js
Fixes opentrials/opentrials#646
Desired changes:
- stop `reindex` if indexing errors are encountered
- delete the new (unfinished) index and fallback to the old one if errors are encountered
- show errors
To test add `dynamic: 'strict',` [in the `trials` index mapping](https://github.com/opentrials/api/blob/master/tools/indexers/trials.js#L17) (on the same level with `properties`).
> [#646] Stop reindex at ElasticSearch error and keep old index

- .travis.yml
- migrations/20170407155833_change-pubmed-source-type-to-journal.js
- seeds/trials.js
Cannot alter type enum, since knex doesn't work as one would expect, by creating a new type represented by an enum. Which is super convenient, given how painful is to alter types (can hardly add new enum values, cannot easily remove them).
Long story short: new migration to add a new `sources.type` for PubMed, named `journal` by replacing the check constraint in place. Rollback possible.
> [#708] Change PubMed source type to 'journal'

- test/e2e/sources.js
This increases our confidence that the sources API responses are valid.
> Add e2e sources test
