opentrials/api

api/controllers/search.js, test/api/controllers/search.js
Fixes opentrials/opentrials#66
=> [#66] Set "AND" as the default operator for ElasticSearch

migrations/20160216120159_create_initial_schema.js
It fixes https://github.com/opentrials/opentrials/issues/77
=> fixed race conditions in migration

migrations/20160415172210_remove_trials_trialrecords_table.js, seeds/trials.js
The relationship between Trial and Trialrecords is one-to-many, so there's no
need for a relationship table.
@roll please take a look
=> Remove trials_trialrecords table and add sources and trialrecords seeds

README.md
Part of opentrials/opentrials#35
=> [#35] Add install instructions

api/models/record.js, api/models/source.js, migrations/20160519105352_rename_trialrecords_to_records.js, seeds/trials.js, test/common.js
Related to opentrials/opentrials#97
=> [#97] Rename trialrecords to records

migrations/20160523160519_trials_remove_not_null.js
Irregularity of data dictates to be less tight on some fields..
=> removed not null fields from trials table

api/models/condition.js, api/models/intervention.js, api/models/organisation.js, api/models/person.js, api/models/trial.js, api/swagger/swagger.yaml, migrations/20160519151639_remove_unused_columns.js, seeds/trials.js, test/api/models/condition.js, test/api/models/intervention.js, test/api/models/location.js, test/api/models/organisation.js, test/api/models/person.js, test/api/models/trial.js, test/factory.js, tools/create-trials-index.js
=> Remove unused fields

api/controllers/trials.js, api/models/record.js, package.json, test/api/controllers/trials.js
Related to opentrials/opentrials#191
=> Reduce memory usage

api/models/trial.js, test/api/models/trial.js
Fixes opentrials/opentrials#192
=> [#192] Ignore Trials without registration_date on yearly trial count

api/controllers/search.js, test/api/controllers/search.js
Fixes opentrials/opentrials#186
=> [#186] Sort trials results by registration_date and _score

api/models/trial.js, test/api/models/trial.js
Fixes opentrials/opentrials#206
=> [#206] Ignore whitespaces and punctuation when calculating discrepancies

api/models/document.js, api/swagger/swagger.yaml, migrations/20160816113418_add_fda_application_number_to_interventions.js, migrations/20160818182848_create_fda_approvals_and_add_relationship_with_documents.js, migrations/20160818194716_add_documentcloud_url_and_text_to_documents.js, seeds/trials.js
This adds the new tables and changes necessary for the FDA processor. Here I'm just creating/changing the tables, and not adding new entities and API endpoints yet. Related to https://github.com/opentrials/collectors/pull/34 and https://github.com/opentrials/processors/pull/38.
opentrials/opentrials#302
=> Changes to the database schema needed for the FDA processor

api/swagger/swagger.yaml, migrations/20160826145535_add_document_type_csr_synopsis.js
=> [#330] Add document type "csr_synopsis"

api/models/record.js, api/models/trial.js, test/api/models/trial.js
@nightsh I'm merging this before your review because I'd like to calculate the new discrepancies today. Please do review when you see this and we can change as needed.
=> [#354] Update fields used to calculate discrepancies

.travis.yml, config/index.js, docker-compose.yml
opentrials/opentrials#359
@roll Merging this as it might solve our ES issues on production, but please take a look when you have a few minutes.
=> [#359] Migrate ElasticSearch 1.5 -> 2.3

api/swagger/swagger.yaml, migrations/20160901174427_add_document_type_results.js, migrations/20160902123540_documents_trial_id_url_and_fda_approval_id_must_be_unique.js
Please check the commit messages for more info.
opentrials/opentrials#289
=> Add results document type and changes documents uniqueness constraint

api/swagger/swagger.yaml, migrations/20160908171543_remove_documents_url_documentcloud_id_and_text_and_set_file_id_as_not_nullable.js, seeds/trials.js, test/factory.js
I migrated the data manually to the new schema (see
591eba12). Now we're ready to remove the unused fields.
Fixes opentrials/opentrials#387
=> [#387] Clean Documents table removing unused fields

api/controllers/sources.js, api/models/source.js, api/swagger/swagger.yaml, migrations/20160907113052_add_url_and_terms_and_conditions_url_to_sources.js, seeds/trials.js, test/api/controllers/sources.js, test/factory.js
=> [#281] Add "url" and "terms_and_conditions_url" to Source

config/index.js
=> [#433] Print errors on console

.eslintrc, config/index.js, npm-shrinkwrap.json, package.json, seeds/trials.js, tools/create-trials-index.js
Fixes opentrials/opentrials#436
=> [#436] Use an eslint AirBnB config that doesn't require React

api/swagger/swagger.yaml, test/api/controllers/stats.js
As requested in opentrials/opentrials#431
=> Remove stats endpoint

config/index.js
=> [#426] Send log messages to stdout

api/swagger/swagger.yaml, seeds/trials.js
Fixes opentrials/opentrials#459
=> [#459] Add missing intervention type

api/models/trial.js, test/api/models/trial.js
Fixes opentrials/opentrials#486
=> [#486] Ignore ICTRP when calculating discrepancies

api/models/document.js, api/models/file.js, api/models/source.js, api/models/trial.js, api/swagger/swagger.yaml, migrations/20161024144543_rename_documents_files_and_sources_url_to_source_url.js, seeds/trials.js, test/api/models/document.js, test/factory.js
=> [#522] Rename url column for documents, files and sources

api/controllers/documents.js, api/controllers/search.js, api/models/document.js, api/models/fda_application.js, api/models/fda_approval.js, api/models/file.js, api/models/trial.js, api/swagger/swagger.yaml, config/index.js, migrations/20161026164912_alter_files_text_to_array_and_rename_to_pages.js, seeds/trials.js, test/api/controllers/documents.js, test/api/controllers/search.js, test/api/models/document.js, test/api/models/fda_application.js, test/api/models/file.js, test/api/models/trial.js, test/e2e/search.js, test/factory.js, tools/indexers/fda_documents.js, tools/indexers/helpers.js, tools/indexers/index.js
See the commit messages for more background on what was done and why. This fixes opentrials/opentrials#500.
=> Add /v1/search/fda_documents endpoint

tools/reindex.js
You can run, for example, `npm run reindex trials fdaDocuments` to reindex only
these two indexes. Now that we're indexing FDA Documents as well, the indexing
process can take a long time, so it's useful to be able to only index the few
that changed.
=> Allow running individual indexers

tools/indexers/fda_documents.js
Fixes opentrials/opentrials#555
=> [#555] Fix FDA Docs indexer when working on files without pages

api/controllers/search.js, api/swagger/swagger.yaml, test/api/controllers/search.js, test/e2e/search.js, tools/indexers/fda_documents.js
See the commit messages.
opentrials/opentrials#501
=> FDA Document search API tweaks for the search UI

.env.example, README.md
As a beginner contributor I've faced some minor issues when setting up the project for the first time in my local machine. These were the adjustments I had to do in order to be able to run the project properly
=> Improve documentation to support local deploy

migrations/20161209163721_add_unique_constraint_to_records_source_url.js
=> [#602] Add unique constraint to records source_url

api/swagger/swagger.yaml, migrations/20170125090419_add_status_unknown_to_trials_and_records.js
=> [#653] Add "unknown" status to Trial and Record

.travis.yml, README.md, npm-shrinkwrap.json, package.json
Fixes opentrials/opentrials#531
=> [#531] Upgrade to Node 6.9.1

api/models/trial.js, api/swagger/swagger.yaml, seeds/trials.js, test/api/models/trial.js, tools/indexers/trials.js
=> Add `is_registered` boolean to identify unregistered trials

tools/indexers/helpers.js
Fixes opentrials/opentrials#693
=> [#693] Fix issue when reindexing trials and stop indexing on error

api/models/trial.js, api/swagger/swagger.yaml, seeds/trials.js, test/api/controllers/conditions.js, test/api/controllers/documents.js, test/api/controllers/fda_applications.js, test/api/controllers/interventions.js, test/api/controllers/organisations.js, test/api/controllers/persons.js, test/api/controllers/publications.js, test/api/controllers/sources.js, test/api/controllers/trials.js, tools/indexers/trials.js
Fixes opentrials/opentrials#709
=> [#709] Expose phase data

api/swagger/swagger.yaml, test/api/controllers/search.js, tools/indexers/autocomplete.js
=> [#651] Disable autocomplete except on locations

tools/indexers/autocomplete.js, tools/indexers/fda_documents.js, tools/indexers/trials.js
Fixes opentrials/opentrials#647
=> [#647] Strict mapping for ElasticSearch

migrations/20170216104317_create_audit_log_for_trial_deduplication.js
This contains the code from https://github.com/opentrials/api/pull/147. I had to create a new PR because I couldn't change the branch on the other PR.
=> [#661] Audit log for trial deduplication

api/models/trial.js, api/swagger/swagger.yaml, test/api/controllers/trials.js, test/api/models/trial.js, tools/indexers/trials.js
Linked to opentrials/opentrials#758
=> [#758] Remove `is_registered` property from trials

migrations/20170419122022_make-is_primary-not-nullable.js
Linked to opentrials/opentrials#757
=> [#757] Record's `is_primary` should not be null

api/models/trial.js, api/swagger/swagger.yaml, migrations/20170221113629_add_age_range_column_to_trials_and_records.js, seeds/trials.js, test/api/controllers/trials.js, test/factory.js, tools/indexers/trials.js
Related to opentrials/opentrials#173
=> [#173] Add migrations and expose trial's "age_range"

api/swagger/swagger.yaml, seeds/trials.js, test/factory.js, tools/indexers/trials.js
Also fixes the seeds when there are values in the "trial_deduplication_logs"
table.
opentrials/opentrials#173
=> [#173] Rename "minimum" and "maximum" to "min" and "max"
